### ISSUE TITLE
introduce icon namespace

### ISSUE THREAD

**Issue by danielleroux** [siemens/ix#343]
#### ToDo

- [ ] Enhance documentation of ix-icons how you can create new icon fonts (based on a clone/fork)
- [ ] Replace all usesages of icons in ix with namespace format
- [ ] Move icon component to ix-icons project

Syntax:
```
<ix-icon name="bulb"></ix-icon> ---> glyph glyph-bulb
<ix-icon name="custom:bulb"></ix-icon> --->  custom custom-bulb
<ix-icon-button name="bulb">
<ix-icon-button name="custom:bulb">
```
